version: "3"
services:
  nest-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql-db

  mysql-db:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
